{
    'name': 'Estate module(tutorial)',
    'version': '1.0',
    'depends':['base', ],
    'application': True,
    'installable': True,
    'data': ['security/ir.model.access.csv',
             'views/estate_menus.xml',
             'views/estate_property_views.xml',
             'views/estate_property_type_views.xml',
             'views/estate_property_tag_views.xml',
             'views/estate_property_offer_views.xml',
             'views/inherited_users_views.xml',
             ],
    'license': 'AGPL-3',
}